version: "3"

services:
  octobot:
    image: drakkarsoftware/octobot:stable
    command: |
      sh -e -c '
        VENV=/opt/venv/bin/python
        # 1. upgrade ccxt inside OctoBot venv
        $VENV -m pip install --no-cache-dir --force-reinstall "ccxt>=4.4.60"
      
        # 2. hot-patch Indodax (limits + 24 h volume)
        $VENV - << "PY"
        import importlib.util, pathlib, sys, ccxt
        spec = importlib.util.spec_from_file_location(
        "indodax_fix", pathlib.Path("/octobot/user/indodax_fix.py"))
        mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
        print(">> Indodax patch loaded; ccxt", ccxt.__version__, file=sys.stderr)
        PY
    
        # 3. launch OctoBot
        exec $VENV -m octobot -c /conf/config.yaml
        '
    volumes:
      - ./logs:/octobot/logs
      - ./backtesting:/octobot/backtesting
      - ./tentacles:/octobot/tentacles
      - ./user:/octobot/user
    ports:
      - ${PORT:-5001}:${PORT:-5001}
    restart: always

  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --cleanup --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
