version: "3"

services:
  octobot:
    image: drakkarsoftware/octobot:stable
    entrypoint: >
      sh -c '
        # 1) Let OctoBot’s wrapper finish its self‑updates first
        /usr/local/bin/docker-entrypoint.sh &   # original ENTRYPOINT in bg
        pid=$!
        wait $pid                              # <- after this, octobot‑trading will have pulled ccxt 4.4.x
      
        # 2) Hard‑pin ccxt without touching dependencies
        /opt/venv/bin/pip install --no-cache-dir --force-reinstall --no-deps "ccxt==4.3.85"
      
        # 3) Launch OctoBot the normal way
        exec /opt/venv/bin/octobot -c /conf/config.yaml
      '
    volumes:
       - ./logs:/octobot/logs
       - ./backtesting:/octobot/backtesting
       - ./tentacles:/octobot/tentacles
       - ./user:/octobot/user
    ports:
       - ${PORT:-5001}:${PORT:-5001}
    restart: always

  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --cleanup --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
