version: "3"

services:
  octobot:
    image: drakkarsoftware/octobot:stable
    entrypoint: >
      sh -c "
        /opt/venv/bin/pip install --no-cache-dir --force-reinstall --no-deps 'ccxt==4.3.85' &&
        exec /opt/venv/bin/python -m octobot -c /conf/config.yaml
      "
    volumes:
       - ./logs:/octobot/logs
       - ./backtesting:/octobot/backtesting
       - ./tentacles:/octobot/tentacles
       - ./user:/octobot/user
    ports:
       - ${PORT:-5001}:${PORT:-5001}
    restart: always

  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --cleanup --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
