# OctoBot minimal configuration for Indodax DRX/IDR trading

exchange-api-key: {}

exchange-encrypted-api-keys: {}

services: {}

notification: {}

profiles:
  default: Market making_(copy)
  loaded: Market making_(copy)

# Set volume multiplier to handle low liquidity
trading-settings:
  minimal-initial-volume-per-order: 0.1
  market-retention-volume-factor: 0.5
  portfolio-equity-percentage: 100

# Set Indodax as exchange and DRX/IDR as trading pair
exchanges:
  indodax:
    api-key: ""
    api-secret: ""
    api-password: ""
    web-auth: null
    sandboxed: false
    exchange-type: SPOT
    future-leverage-tiers: null
    futures-contract-settings: {}

    enabled: true
    selected-leverage: null

# Set up DRX/IDR trading pair
crypto-currencies:
  DRX:
    pairs:
      - DRX/IDR

# Use market making trading mode
trading-modes:
  MarketMakerTradingMode:
    required-strategies:
      daily-trading-mode-strategy:
        enable: false
        market-status:
          enable: false
        price-data:
          enable: false
    pairs:
      indodax:
        - DRX/IDR

# Prevent OctoBot from making any trades
trader:
  enabled: true
  load-trade-history: true

# Disable simulated trading
simulator:
  enabled: false
  fees:
    maker: 0.1
    taker: 0.1

# Increased log level for debugging
logging-level: INFO

# Basic trading mode settings
market-maker-setting:
  DRX/IDR:
    side: both
    ref-market-min-max: null
    starting-price: 150
    flat-spread: true
    spread-percent: 5
    increment-percent: 0.5
    double-spread-after: 5
    max-increment: 10
    max-living-orders-per-side: 10
    stop-loss-enabled: false
    stop-loss-limit-offset-percent: 5
    stop-loss-price: null
    order-size: 1250
    refresh-orders-threshold-percent: 5
    use-existing-orders-only: false
    convert-symbol-with-mark-price: true
    allow-instant-fill: true
    disable-price-restriction: true
    price-filter: 0
    allocation-strategy: proportional
